sudo: required
services:
  - docker
before_build:
  - docker build -t 64c5325dd5d6 -f Dockerfile.dev .
script:
  - docker run -e CI=true 64c5325dd5d6 npm test -- --coverage

after_success:
  - docker build -t 64c5325dd5d6 .
  - echo "$DOCKER_PASSWORD" | docker login  --username "$DOCKER_ID" --password-stdin 
  - docker push 64c5325dd5d6

