version: '3.9'
services:
  server:
    image: rohail32/server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://rohail:nitricacid@ecommerceapp.iyvkf3w.mongodb.net/?retryWrites=true&w=majority
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - server
    volumes:
      - ./node_modules:/frontend/node_modules
      - ./:/frontend
    stdin_open: true
    ports:
      - "3000:3000"


