version: '3.9'
services:
  server:
    image: rohail32/server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - server
    volumes:
      - ./node_modules:/client/node_modules
      - ./:/client
    stdin_open: true
    ports:
      - "3000:3000"


